spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
          filters:
            - StripPrefix=0
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**, /api/enrollments/**
          filters:
            - StripPrefix=0
        - id: eureka-server
          uri: lb://eureka-server
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=0
        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**
          filters:
            - StripPrefix=1
        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/api/exams/**, /api/courses/**, /api/users/**
          filters:
            - StripPrefix=0

server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

globalcors:
  corsConfigurations:
    '[/**]':
      allowedOrigins: "*"
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
      allowedHeaders: "*"
      exposedHeaders: "Authorization" 