server:
  port: 8085

spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/payment_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      enrollmentClient:
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5000
        permitted-number-of-calls-in-half-open-state: 3
  retry:
    instances:
      enrollmentClient:
        max-attempts: 3
        wait-duration: 1000
  timelimiter:
    instances:
      enrollmentClient:
        timeout-duration: 3000

# Feign Configuration
feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        loggerLevel: FULL

jwt:
  secret: "A1b2C3d4E5f6G7h8I9j0K1l2M3n4O5p6"
  expiration: 86400000

logging:
  level:
    com.example.payment_service.client.UserClient: DEBUG
    feign: DEBUG

gateway:
  url: http://localhost:8083 